name: Build LaTeX document
on:
  push:
    branches:
      - main
    # paths:
    # - "**.tex"

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/texlive-action/small@v1
        with:
          run: |
            apk add make
            make build
      - name: "Generate index"
        run: |
          python generate_index.py
          find . -type f -iname "*.pdf"

      - name: Push pdfs to gh-pages branch
        run: |
          git config user.name github-actions
          git config user.email actions@github.com
          git fetch origin gh-pages:gh-pages
          git stash
          git checkout gh-pages
          git stash apply
          git add '*.pdf'
          git commit -m "delivery!"
          git push origin gh-pages
      #   uses: JamesIves/github-pages-deploy-action@4.1.5
      #   with:
      #     branch: gh-pages
      #     folder: pdfs
      #     git-config-name: github-actions
      #     git-config-email: github-actions[bot]@users.noreply.github.com
