name: Build LaTeX document
on:
  push:
    branches:
      - main
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: test.tex
          post_compile: |
            latexmk -c
            mkdirs pdfs
            mv *.pdf pdfs/
      # - name: Hide file
      #   run: mkdir pdfs; mv *.pdf pdfs/
      - name: Push pdfs to gh-pages branch
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: pdfs
        # uses: EndBug/add-and-commit@v7
        # with:
        #   add: "*.pdf --force"
        #   branch: gh-pages
        #   message: "new pdf"
        # commit_message: new pdf
        # branch: gh-pages
        # push_options: "--force"
