name: Build LaTeX documents and deploy to GitHub pages
on:
  push:
    branches:
      - main
    paths:
      - "**.tex"

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        # with:
        #   fetch-depth: 0

      - name: Get changed files
        id: changed-tex-files
        uses: tj-actions/changed-files@v11
        with:
          files: |
            *\.tex$

      - name: setup latex
        uses: xu-cheng/texlive-action/small@v1
        with:
          run: |
            for file in ${{ steps.changed-tex-files.outputs.all_modified_files }}; do
              latexmk -pdf $file
            done

      - name: Run step if any of the listed files above is deleted
        if: steps.changed-files.outputs.any_deleted == "true"
        run: |
          for file in ${{ steps.changed-files.outputs.deleted_files }}; do
            rm $file
          done

      - name: Push pdfs to gh-pages branch
        run: |
          git config user.name github-actions
          git config user.email actions@github.com
          git fetch origin gh-pages:gh-pages
          mv generate_index.py index.py
          git stash --all
          git checkout gh-pages
          for file in ${{ steps.changed-tex-files.outputs.all_modified_files }}; do
            rm "${file%.*}.pdf"
          done
          git stash pop
          python index.py
          git add '*.pdf' README.md
          git commit -m "delivery! initiated from ($GITHUB_SHA)"
          git push origin gh-pages
